import * as icons from "../components/icons/";

export const randomCardList = [
  {
    id: 0,
    title: "1M",
    amount: "1M",
    bg: "/imgs/green.png",
    icon: icons.CashIcon,
    image: "/imgs/cash.png",
  },
  {
    id: 1,
    title: "100",
    amount: "100",
    bg: "/imgs/green.png",
    icon: icons.CashIcon,
    image: "/imgs/cash.png",
  },
  {
    id: 2,
    title: "1000",
    amount: "1000",
    bg: "/imgs/green.png",
    icon: icons.CashIcon,
    image: "/imgs/cash.png",
  },
  {
    id: 3,
    title: "500",
    amount: "500",
    bg: "/imgs/green.png",
    icon: icons.CashIcon,
    image: "/imgs/cash.png",
  },
  {
    id: 4,
    title: "10K",
    amount: "10K",
    bg: "/imgs/green.png",
    icon: icons.CashIcon,
    image: "/imgs/cash.png",
  },
  {
    id: 5,
    title: "Multiplier",
    amount: "x2",
    bg: "/imgs/blue.png",
    icon: icons.X2CardIcon,
    image: "/imgs/x2Icon.png",
  },
  {
    id: 6,
    title: "Stop",
    amount: "stop",
    bg: "/imgs/gray.png",
    icon: icons.StopIcon,
    image: "/imgs/stopIcon.png",
  },
  {
    id: 7,
    title: "Bomb",
    amount: "bomb",
    bg: "/imgs/red.png",
    icon: icons.BombIcon,
    image: "/imgs/bombIcon.png",
  },
  {
    id: 8,
    title: "Zero",
    amount: "0",
    bg: "/imgs/yellow.png",
    icon: icons.ZeroIcon,
    image: "/imgs/0Icon.png",
  },
];
